#!/usr/bin/env bash
# Builds the Sprig stage-0 compiler: grammar generation + compiler + runtime.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANTLR_JAR="${ANTLR_JAR:-$ROOT/tools/antlr-4.13.2-complete.jar}"
ANTLR_SHA256="eae2dfa119a64327444672aff63e9ec35a20180dc5b8090b7a6ab85125df4d76"

if [[ ! -f "$ANTLR_JAR" ]]; then
  echo "Downloading ANTLR4 4.13.2 complete JAR (official Maven Central release)..."
  mkdir -p "$ROOT/tools"
  curl -fsSL -o "$ANTLR_JAR" \
    https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.13.2/antlr4-4.13.2-complete.jar
fi

actual_sha256="$(shasum -a 256 "$ANTLR_JAR" | awk '{print $1}')"
if [[ "$actual_sha256" != "$ANTLR_SHA256" ]]; then
  echo "ANTLR4 JAR checksum mismatch: expected $ANTLR_SHA256, got $actual_sha256" >&2
  exit 2
fi

command -v java >/dev/null || { echo 'JDK required' >&2; exit 2; }
command -v javac >/dev/null || { echo 'JDK required' >&2; exit 2; }

BUILD="$ROOT/build"
rm -rf "$BUILD/gen" "$BUILD/classes" "$BUILD/sprig-compiler.jar"
mkdir -p "$BUILD/gen" "$BUILD/classes"

echo "Generating ANTLR4 parser..."
(cd "$ROOT/grammar" && java -jar "$ANTLR_JAR" -Dlanguage=Java -visitor -no-listener \
  -package sprig.compiler.parser -o "$BUILD/gen" SprigLexer.g4)
(cd "$ROOT/grammar" && java -jar "$ANTLR_JAR" -Dlanguage=Java -visitor -no-listener \
  -package sprig.compiler.parser -lib "$BUILD/gen" -o "$BUILD/gen" SprigParser.g4)

echo "Compiling compiler + runtime..."
find "$BUILD/gen" "$ROOT/compiler/src/main/java" "$ROOT/runtime/src/main/java" -name '*.java' \
  > "$BUILD/sources.txt"
javac --release 17 -encoding UTF-8 -Xlint:-options -cp "$ANTLR_JAR" \
  -d "$BUILD/classes" @"$BUILD/sources.txt"
if [[ -d "$ROOT/compiler/src/main/resources" ]]; then
  cp -R "$ROOT/compiler/src/main/resources/." "$BUILD/classes/"
fi

# A single compiler JAR avoids partial/duplicated class trees (e.g. cloud-sync
# conflict copies inside a synced Desktop folder) breaking the launcher.
jar --create --file "$BUILD/sprig-compiler.jar" -C "$BUILD/classes" .

mkdir -p "$ROOT/bin"
cat > "$ROOT/bin/sprig" <<EOF
#!/usr/bin/env bash
# Sprig compiler launcher generated by scripts/build.sh
SPRIG_OUTPUT="$ROOT"
exec java -cp "\$SPRIG_OUTPUT/build/sprig-compiler.jar:$ANTLR_JAR" -Dsprig.home="\$SPRIG_OUTPUT" \\
  sprig.compiler.cli.Main "\$@"
EOF
chmod +x "$ROOT/bin/sprig"

if ! "$ROOT/bin/sprig" version >/dev/null 2>&1; then
  echo "Build sanity check failed: compiler launcher cannot start." >&2
  echo "If the output folder is cloud-synced, wait for sync and rebuild." >&2
  exit 1
fi

echo "Built Sprig stage-0 compiler."
echo "  launcher:  $ROOT/bin/sprig"
echo "  classes:   $BUILD/classes"
echo "  compiler:  $BUILD/sprig-compiler.jar"
echo "  ANTLR jar: $ANTLR_JAR"
