[package]
name = "cli"
description = "Explicit command-line option parsing and usage text"
git = "https://github.com/ColinHouse/Sprig.git"
subdir = "libraries/sprig-cli"

[[release]]
version = "0.7.1-beta.1"
tag = "v0.7.1-beta.1"
