[package]
name = "http"
description = "Small synchronous JDK HTTP/HTTPS client"
git = "https://github.com/ColinHouse/Sprig.git"
license = "Apache-2.0"
owners = ["ColinHouse"]
subdir = "libraries/sprig-http"

[[release]]
version = "0.7.1-beta.1"
tag = "v0.7.1-beta.1"
rev = "b7fe68eb1cc98cb018f1d07e472d69d73acf4328"
